resolver 8.8.8.8 valid=30s;

server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/ {
        set $backend_upstream https://backend-api-866z.onrender.com;
        proxy_pass $backend_upstream/api/;
        proxy_set_header Host backend-api-866z.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }

    location /monitor/ {
        set $monitor_upstream https://monitor-service-s916.onrender.com;
        proxy_pass $monitor_upstream/;
        proxy_set_header Host monitor-service-s916.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }

    location /logs/ {
        set $logs_upstream https://log-analyzer-c084.onrender.com;
        proxy_pass $logs_upstream/;
        proxy_set_header Host log-analyzer-c084.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }
}